<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Citizen Incident Reports - Export</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #059669;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #065f46;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8fafc;
            color: #475569;
            text-transform: uppercase;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        @media print {
            body { padding: 0; }
            button { display: none; } /* Hide any buttons during actual print */
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>Waste Management Information System</h1>
        <p>Citizen Incident Reports Official Export</p>
        <p>Generated on: {{ \Carbon\Carbon::now()->format('Y-m-d H:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%">ID</th>
                <th style="width: 20%">Citizen</th>
                <th style="width: 15%">Issue Type</th>
                <th style="width: 40%">Description</th>
                <th style="width: 10%">Status</th>
                <th style="width: 10%">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
                <tr>
                    <td>#{{ $report->id }}</td>
                    <td>{{ $report->citizen ? $report->citizen->name : 'Anonymous' }}</td>
                    <td>{{ $report->issue_type }}</td>
                    <td>{{ $report->description }}</td>
                    <td>{{ $report->status }}</td>
                    <td>{{ $report->created_at->format('Y-m-d') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Confidential Municipal Document • Generated by WMIS • Page 1 of 1
    </div>

    <script>
        // Automatically trigger print dialog when page loads
        window.onload = function() {
            window.print();
            // Optional: Close tab or go back after printing dialog is closed
            // setTimeout(function(){ window.close(); }, 500); 
        };
    </script>
</body>
</html>
